version: "3.8"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  bot:
    image: {TAG_COMMIT}
    env_file: .env
    restart: always
    networks:
      - default

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://animebot_user:IetooyahSee1oZea5eiwohjohrahf5ieLa7Vah0xohbufee6@localhost:5432/animebot?sslmode=disable", "up"]
    links: 
      - database
    depends_on:
      - database
    networks:
      - default

networks:
  default: 