alter table "users" add column if not exists "shikimori" text not null default '';

create table if not exists "genres" (
    "id"        bigserial   PRIMARY KEY,
    "name"      text        not null,
    "russian"   text        not null,
    "kind"      text        not null
)

create table if not exists "anime_list" (
    "id"            bigserial   PRIMARY KEY,
    "shikimory_id"  bigint      not null unique,
    "name"          text        not null,
    "russian"       text        not null,
    "url"           text        not null,
    "status"        text        not null,
    "score"         int         not null,
    "episodes"      int         not null,
    "year"          int         not null,
    "rating"        text        not null,
    "description"   text        not null,
    "image_url"     text        not null,
    "genres"        int[]       not null default '{}'
) 

create table if not exists "evaluations" (
    "user_id"       bigint      not null,
    "anime_id"      bigint      not null,
    "score"         int         not null,
    "created_at"    timestamp   not null default 'now()'
);

create unique index if not exists "idx_unique_evaluations" on "evaluations" ("user_id", "anime_id");

insert into "genres" ("id", "name", "russian", "kind") values
    ('89', 'Police', 'Полиция', 'manga'),
    ('8', 'Drama', 'Драма', 'anime'),
    ('11', 'Game', 'Игры', 'anime'),
    ('40', 'Psychological', 'Психологическое', 'anime'),
    ('67', 'Psychological', 'Психологическое', 'manga'),
    ('72', 'Demons', 'Демоны', 'manga'),
    ('79', 'Game', 'Игры', 'manga'),
    ('87', 'Josei', 'Дзёсей', 'manga'),
    ('2', 'Adventure', 'Приключения', 'anime'),
    ('75', 'Yuri', 'Юри', 'manga'),
    ('47', 'Shounen', 'Сёнен', 'manga'),
    ('49', 'Comedy', 'Комедия', 'manga'),
    ('48', 'Supernatural', 'Сверхъестественное', 'manga'),
    ('50', 'Drama', 'Драма', 'manga'),
    ('51', 'Ecchi', 'Этти', 'manga'),
    ('63', 'Shoujo', 'Сёдзе', 'manga'),
    ('64', 'Vampire', 'Вампиры', 'manga'),
    ('65', 'Yaoi', 'Яой', 'manga'),
    ('19', 'Music', 'Музыка', 'anime'),
    ('88', 'Samurai', 'Самураи', 'manga'),
    ('56', 'Action', 'Экшен', 'manga'),
    ('86', 'Parody', 'Пародия', 'manga'),
    ('54', 'Slice of Life', 'Повседневность', 'manga'),
    ('68', 'Adventure', 'Приключения', 'manga'),
    ('78', 'Music', 'Музыка', 'manga'),
    ('80', 'Horror', 'Ужасы', 'manga'),
    ('83', 'Mecha', 'Меха', 'manga'),
    ('62', 'Romance', 'Романтика', 'manga'),
    ('542', 'Work Life', 'Работа', 'manga'),
    ('543', 'Gourmet', 'Гурман', 'anime'),
    ('544', 'Gourmet', 'Гурман', 'manga'),
    ('69', 'Historical', 'Исторический', 'manga'),
    ('1', 'Action', 'Экшен', 'anime'),
    ('4', 'Comedy', 'Комедия', 'anime'),
    ('6', 'Demons', 'Демоны', 'anime'),
    ('39', 'Police', 'Полиция', 'anime'),
    ('57', 'Fantasy', 'Фэнтези', 'manga'),
    ('58', 'Magic', 'Магия', 'manga'),
    ('71', 'Harem', 'Гарем', 'manga'),
    ('76', 'Sports', 'Спорт', 'manga'),
    ('59', 'Hentai', 'Хентай', 'manga'),
    ('29', 'Space', 'Космос', 'anime'),
    ('60', 'School', 'Школа', 'manga'),
    ('85', 'Space', 'Космос', 'manga'),
    ('9', 'Ecchi', 'Этти', 'anime'),
    ('10', 'Fantasy', 'Фэнтези', 'anime'),
    ('12', 'Hentai', 'Хентай', 'anime'),
    ('13', 'Historical', 'Исторический', 'anime'),
    ('14', 'Horror', 'Ужасы', 'anime'),
    ('16', 'Magic', 'Магия', 'anime'),
    ('18', 'Mecha', 'Меха', 'anime'),
    ('20', 'Parody', 'Пародия', 'anime'),
    ('21', 'Samurai', 'Самураи', 'anime'),
    ('22', 'Romance', 'Романтика', 'anime'),
    ('23', 'School', 'Школа', 'anime'),
    ('539', 'Erotica', 'Эротика', 'anime'),
    ('27', 'Shounen', 'Сёнен', 'anime'),
    ('32', 'Vampire', 'Вампиры', 'anime'),
    ('33', 'Yaoi', 'Яой', 'anime'),
    ('34', 'Yuri', 'Юри', 'anime'),
    ('35', 'Harem', 'Гарем', 'anime'),
    ('53', 'Sci-Fi', 'Фантастика', 'manga'),
    ('36', 'Slice of Life', 'Повседневность', 'anime'),
    ('26', 'Shoujo Ai', 'Сёдзё-ай', 'anime'),
    ('540', 'Erotica', 'Эротика', 'manga'),
    ('43', 'Josei', 'Дзёсей', 'anime'),
    ('74', 'Gender Bender', 'Смена пола', 'manga'),
    ('61', 'Doujinshi', 'Додзинси', 'manga'),
    ('81', 'Thriller', 'Триллер', 'manga'),
    ('37', 'Supernatural', 'Сверхъестественное', 'anime'),
    ('41', 'Thriller', 'Триллер', 'anime'),
    ('24', 'Sci-Fi', 'Фантастика', 'anime'),
    ('25', 'Shoujo', 'Сёдзё', 'anime'),
    ('31', 'Super Power', 'Супер сила', 'anime'),
    ('82', 'Super Power', 'Супер сила', 'manga'),
    ('46', 'Mystery', 'Детектив', 'manga'),
    ('38', 'Military', 'Военное', 'anime'),
    ('7', 'Mystery', 'Детектив', 'anime'),
    ('70', 'Military', 'Военное', 'manga'),
    ('15', 'Kids', 'Детское', 'anime'),
    ('77', 'Kids', 'Детское', 'manga'),
    ('3', 'Cars', 'Машины', 'anime'),
    ('84', 'Cars', 'Машины', 'manga'),
    ('17', 'Martial Arts', 'Боевые искусства', 'anime'),
    ('66', 'Martial Arts', 'Боевые искусства', 'manga'),
    ('5', 'Dementia', 'Безумие', 'anime'),
    ('90', 'Dementia', 'Безумие', 'manga'),
    ('30', 'Sports', 'Спорт', 'anime'),
    ('541', 'Work Life', 'Работа', 'anime'),
    ('42', 'Seinen', 'Сэйнэн', 'anime'),
    ('28', 'Shounen Ai', 'Сёнен-ай', 'anime'),
    ('73', 'Shoujo Ai', 'Сёдзе-ай', 'manga'),
    ('55', 'Shounen Ai', 'Сёнен-ай', 'manga'),
    ('52', 'Seinen', 'Сэйнэн', 'manga');
